---
- name: Download GitLab runner apt script
  ansible.builtin.get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: "/tmp/script.deb.sh"
    mode: 0755

- name: Add apt repository for GitLab Runner
  ansible.builtin.shell: "/tmp/script.deb.sh"
  args:
    executable: /bin/bash

- name: Update apt and install GitLab Runner
  ansible.builtin.apt:
    pkg:
      - gitlab-runner
    state: present
    update_cache: true

- name: Create script for registration from j2 template
  ansible.builtin.template:
    src: "runner_register.j2"
    dest: "gitlab-runner-register"
    owner: root
    group: root
    mode: 0755

- name: Delay befor registration Runner
  ansible.builtin.shell: "sleep 100"

- name: Register GitLab Runner
  ansible.builtin.shell: "./gitlab-runner-register"

