---
- name: Create the alertmanager group
  ansible.builtin.group:
    name: alertmanager
    state: present
    system: true

- name: Create the alertmanager user
  ansible.builtin.user:
    name: alertmanager
    groups: alertmanager
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /

- name: Download alertmanager binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz"
    dest: "/tmp/alertmanager-0.24.0.linux-amd64.tar.gz"
    mode: 0644
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2

- name: Unpack alertmanager binary
  ansible.builtin.unarchive:
    src: "/tmp/alertmanager-0.24.0.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/alertmanager-0.24.0.linux-amd64/alertmanager"

- name: Copy alertmanager binary file on remote machine
  ansible.builtin.copy:
    src: "/tmp/alertmanager-0.24.0.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    mode: 0755
    owner: root
    group: root
    remote_src: yes

- name: Create a directory /etc/alertmanager if it does not exist
  ansible.builtin.file:
    path: "/etc/alertmanager"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create /etc/alertmanager/alertmanager.yml file from j2 template
  ansible.builtin.template:
    src: "alertmanager.yml.j2"
    dest: "/etc/alertmanager/alertmanager.yml"
    owner: root
    group: root
    mode: 0644

- name: Create a directory /var/lib/alertmanager if it does not exist
  ansible.builtin.file:
    path: "/var/lib/alertmanager"
    state: directory
    mode: 0755
    owner: alertmanager
    group: alertmanager

- name: Create alertmanager.service file from j2 template
  ansible.builtin.template:
    src: "alertmanager.j2"
    dest: "/etc/systemd/system/alertmanager.service"
    owner: root
    group: root
    mode: 0644

- name: Make sure a service alertmanager is running
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: alertmanager