---
- name: Install of requirements tools
  hosts: mysql
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: ubuntu_install_tools

- name: MySQL install
  hosts: mysql
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: mysql_install