
---
- name: Install of requirements tools
  hosts: nginx
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: nginx_install_tools

- name: NGINX install
  hosts: nginx
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: nginx_install

- name: NGINX restart
  hosts: nginx
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - role: nginx_restart