---
- name: Generate an OpenSSH keypair for '{{ username }}' on proxy
  hosts: nginx
  remote_user: ubuntu
  roles:
  - role: gen_ssh_key

- name: Copy ssh key from proxy to inside nodes
  hosts: nodesinside
  remote_user: ubuntu
  roles:
  - role: copy_ssh_key