---
- name: Add docker GPG apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo:  "deb https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename|lower }} stable"
    state: present

- name: Update apt and install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Install docker module for python
  ansible.builtin.pip:
    name: docker

- name: Add user 'ubuntu' to group 'docker'
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
